### ISSUE TITLE
working?

### ISSUE THREAD

**Issue by darkzbaron** [audetto/raireplay#1]
hi there, is that in a working state? thanks for the work, its exactly what i was looking for.

**Comment by audetto** [comment]
Yes it is working
Admittedly some channels better than other, depending on the ones I use most.
RaiPlay is the best I would say.
There is no special setup, you will need this as well

https://github.com/globocom/m3u8

**Comment by darkzbaron** [comment]
Hi Andrea,thanks for the update. Can’t wait to start playing with it!                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        From: AndreaSent: Tuesday, 21 March 2017 21:56To: audetto/raireplayReply To: audetto/raireplayCc: darkzbaron; AuthorSubject: Re: [audetto/raireplay] working? (#1)Yes it is working
Admittedly some channels better than other, depending on the ones I use most.
RaiPlay is the best I would say.
There is no special setup, you will need this as well
https://github.com/globocom/m3u8

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/audetto/raireplay","title":"audetto/raireplay","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/audetto/raireplay"}},"updates":{"snippets":[{"icon":"PERSON","message":"@audetto in #1: Yes it is working\r\nAdmittedly some channels better than other, depending on the ones I use most.\r\nRaiPlay is the best I would say.\r\nThere is no special setup, you will need this as well\r\n\r\nhttps://github.com/globocom/m3u8\r\n\r\n"}],"action":{"name":"View Issue","url":"https://github.com/audetto/raireplay/issues/1#issuecomment-288215916"}}}

**Comment by darkzbaron** [comment]
Hi, there. got it thanks so much. Currently setting up my media server. Do you have any trouble with tf1. I somehow always get this error:

Any thing that I am not understanding in how your software is supposed to work? Thanks again for the great piece of work.

``
Exception: removing C:\Users\Jonathan\video\155221996-Rund_Um.mp4
Exception: [WinError 2] The system cannot find the file specified
``

**Comment by darkzbaron** [comment]
Hi there, it looks like pluzz is broken!

**Comment by darkzbaron** [comment]
"Python36\python.exe" "C:\Users\Jonathan\Dropbox\Toolbox\raireplay\raireplay.py" --pluzz
Failed to download program file: http://webservices.francetelevisions.fr/catchup/flux/flux_main.zip
Exception: HTTP Error 404: Not Found
Failed to download data file: http://webservices.francetelevisions.fr/catchup/flux/flux_main.zip
Traceback (most recent call last):
  File "C:\Users\Jonathan\Dropbox\Toolbox\raireplay\raireplay.py", line 79, in <module>
    main()
  File "C:\Users\Jonathan\Dropbox\Toolbox\raireplay\raireplay.py", line 60, in main
    Driver.process(args)
  File "C:\Users\Jonathan\Dropbox\Toolbox\raireplay\Driver.py", line 190, in process
    Pluzz.download(db, grabber, args.download)
  File "C:\Users\Jonathan\Dropbox\Toolbox\raireplay\asi\Pluzz.py", line 50, in download
    z = zipfile.ZipFile(f, "r")
  File "Python36\lib\zipfile.py", line 1100, in __init__
    self._RealGetContents()
  File "Python36\lib\zipfile.py", line 1163, in _RealGetContents
    endrec = _EndRecData(fp)
  File "Python36\lib\zipfile.py", line 241, in _EndRecData
    fpin.seek(0, 2)
AttributeError: 'NoneType' object has no attribute 'seek'
