### ISSUE TITLE
Pluzz

### ISSUE THREAD

**Issue by darkzbaron** [audetto/raireplay#2]
Hi there, looks like pluzz stopped working

here is the full log:

"Python36\python.exe" "raireplay\raireplay.py" --pluzz
Failed to download program file: http://webservices.francetelevisions.fr/catchup/flux/flux_main.zip
Exception: HTTP Error 404: Not Found
Failed to download data file: http://webservices.francetelevisions.fr/catchup/flux/flux_main.zip
Traceback (most recent call last):
  File "raireplay\raireplay.py", line 79, in <module>
    main()
  File "raireplay\raireplay.py", line 60, in main
    Driver.process(args)
  File "raireplay\Driver.py", line 190, in process
    Pluzz.download(db, grabber, args.download)
  File "raireplay\asi\Pluzz.py", line 50, in download
    z = zipfile.ZipFile(f, "r")
  File "Python36\lib\zipfile.py", line 1100, in __init__
    self._RealGetContents()
  File "Python36\lib\zipfile.py", line 1163, in _RealGetContents
    endrec = _EndRecData(fp)
  File "Python36\lib\zipfile.py", line 241, in _EndRecData
    fpin.seek(0, 2)
AttributeError: 'NoneType' object has no attribute 'seek'

**Comment by audetto** [comment]
Have only been using raiplay recently.
Will have to do some debugging.

**Comment by audetto** [comment]
pluzz is gone.
Now there is a new platform france.tv

No idea how it works nor if it is easy to write a plugin for it.

**Comment by darkzbaron** [comment]
Ok cool, thanks for your great work anyway, definitely the best cli tv catchup out there!

**Comment by audetto** [comment]
If I could at least install the france.tv android app, I could have a go, but I have problems to change the app store country.

If you are able to capture the netwrok traffic of the app, that could help.

**Comment by darkzbaron** [comment]
Yep. Ill do it. What app do you use for traffic capture?                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         From: AndreaSent: Tuesday, 24 October 2017 10:13To: audetto/raireplayReply To: audetto/raireplayCc: darkzbaron; AuthorSubject: Re: [audetto/raireplay] Pluzz (#2)If I could at least install the france.tv android app, I could have a go, but I have problems to change the app store country.
If you are able to capture the netwrok traffic of the app, that could help.

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/audetto/raireplay","title":"audetto/raireplay","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/audetto/raireplay"}},"updates":{"snippets":[{"icon":"PERSON","message":"@audetto in #2: If I could at least install the france.tv android app, I could have a go, but I have problems to change the app store country.\r\n\r\nIf you are able to capture the netwrok traffic of the app, that could help."}],"action":{"name":"View Issue","url":"https://github.com/audetto/raireplay/issues/2#issuecomment-338910477"}}}

**Comment by audetto** [comment]
This is what I do

1) run a http proxy on my PC (I use this https://mitmproxy.org/)
2) on the tablet, in the network configuration, set the proxy to be your PC ip port 8080 (default of mitm)
3) test that network still works on the tablet and mitmproxy shows traffic on the screen
4) close all apps
5) http://docs.mitmproxy.org/en/latest/mitmdump.html to save all output to a file.
6) run france.tv up to a point where you show a video moving.
7) stop everything, remove proxy, send the file
8) if the logic is not too complicated this is normally enough

**Comment by darkzbaron** [comment]
Cool. Let me do that at the weekend and il dump the logs here                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        From: AndreaSent: Tuesday, 24 October 2017 13:17To: audetto/raireplayReply To: audetto/raireplayCc: darkzbaron; AuthorSubject: Re: [audetto/raireplay] Pluzz (#2)This is what I do

run a http proxy on my PC (I use this https://mitmproxy.org/)
on the tablet, in the network configuration, set the proxy to be your PC ip port 8080 (default of mitm)
test that network still works on the tablet and mitmproxy shows traffic on the screen
close all apps
http://docs.mitmproxy.org/en/latest/mitmdump.html to save all output to a file.
run france.tv up to a point where you show a video moving.
stop everything, remove proxy, send the file
if the logic is not too complicated this is normally enough


—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/audetto/raireplay","title":"audetto/raireplay","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/audetto/raireplay"}},"updates":{"snippets":[{"icon":"PERSON","message":"@audetto in #2: This is what I do\r\n\r\n1) run a http proxy on my PC (I use this https://mitmproxy.org/)\r\n2) on the tablet, in the network configuration, set the proxy to be your PC ip port 8080 (default of mitm)\r\n3) test that network still works on the tablet and mitmproxy shows traffic on the screen\r\n4) close all apps\r\n5) http://docs.mitmproxy.org/en/latest/mitmdump.html to save all output to a file.\r\n6) run france.tv up to a point where you show a video moving.\r\n7) stop everything, remove proxy, send the file\r\n8) if the logic is not too complicated this is normally enough\r\n"}],"action":{"name":"View Issue","url":"https://github.com/audetto/raireplay/issues/2#issuecomment-338957090"}}}

**Comment by audetto** [comment]
Read this as well. you might need it

http://docs.mitmproxy.org/en/latest/certinstall.html

I only ever needed for M6 and this before they encrypted the video.
All other channels use http (not https) so it is not required.

**Comment by darkzbaron** [comment]
Did not have time to do it this week end, will do it asap and let you know. have a great week!

**Comment by audetto** [comment]
It's ok.
I had a quick look at the browser page and it uses Flash and what looks like some encryption (which is a very bad sign)

In the past I had more luck with analysing the traffic of the iPhone app: maybe because there is no Flash on iOS and it uses a different (easier?) method. Unfortunately newer apps cannot be installed on my ipod touch as it is too old.

**Comment by audetto** [comment]
I've removed support for Pluzz as it does not work any longer and I have no idea how to fix it.

**Comment by darkzbaron** [comment]
Just got an Android phone Last week-end (i had a Blackberry) will send you the log asap. Sorry for the delay, i did not forget                                                                                                                                                                                                                                                                                                                                                   From: notifications@github.comSent: 13 February 2018 8:37 PMTo: raireplay@noreply.github.comReply to: reply@reply.github.comCc: darkzbaron@hotmail.com; author@noreply.github.comSubject: Re: [audetto/raireplay] Pluzz (#2)  I've removed support for Pluzz as it does not work any longer and I have no idea how to fix it.

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread.

**Comment by darkzbaron** [comment]
I am based in Switzerland and I can't connect to the app. I will have to go in France!
